import Footer from '../components/Footer'
import './Donation.css'
const flow=[['abandoned-cart.svg','Cari Kebutuhan Donasi','Cari barang yang sedang dibutuhkan oleh komunitas di sekitarmu.','Cari Kebutuhan'],['fingers-id.svg','Isi Form Donasi','Sudah tahu barang yang ingin didonasikan? Isi formulir donasi di sini.','Isi Form Donasi'],['families.svg','Komunitas Penerima','Lihat komunitas terverifikasi yang menerima donasi sesuai kategori.','Lihat Komunitas'],['free-shipping.svg','Status Donasi','Pantau status donasi mulai dari verifikasi hingga barang diterima.','Cek Status Donasi']]
const partners=[['sedekas semarang barat 1.svg','Sedekas','Komunitas di Semarang Barat yang mengumpulkan dan menyalurkan barang bekas layak pakai.'],['dipo waste bank 1.svg','Dipo Waste Bank','Bank sampah di lingkungan kampus UNDIP yang menampung sampah terpilah.'],['Panji AL JANNAH 1.svg','Panti Asuhan Al Jannah','Panti asuhan di Semarang yang membina anak yatim, piatu, dan dhuafa.'],['Panti asuhan kristen tanah putih 1.svg','Panti Asuhan Kristen Tanah Putih','Panti asuhan yang membina anak-anak yatim dan kurang mampu.']]
const stats=[['12.400+','Barang Tersirkulasi'],['2.000 kg','Sampah Dikurangi'],['4.680 kg','CO2 Dihemat'],['1.500+','Pengguna Aktif']]
export default function Donation(){return <main className="donation-page">
  <section className="donation-hero"><div><h1>Donasikan Barang,<br/>Berikan Manfaat,<br/><em>Kembalikan Nilai.</em></h1><p>Barang layak pakai milikmu dapat membantu orang lain sekaligus mengurangi limbah. Bersama KEMBALI, wujudkan masa depan yang lebih hijau dan berkelanjutan.</p><div className="donation-actions"><button disabled title="Form donasi belum tersedia">Mulai Donasi Sekarang <span>Segera hadir</span></button><a href="#alur">▶ &nbsp; Pelajari Lebih Lanjut</a></div></div><img src="/design-thinking.svg" alt="Ilustrasi berbagi ide dan barang" /></section>
  <section className="donation-flow" id="alur"><h2>Alur Donasi di KEMBALI</h2><div className="flow-row">{[['Cari Kebutuhan','Temukan barang yang sedang dibutuhkan oleh komunitas.'],['Isi Form Donasi','Lengkapi informasi barang dan data diri dengan mudah.'],['Konfirmasi','Periksa kembali detail donasi dan konfirmasi pengajuan.'],['Tracking Donasi','Pantau proses donasi hingga sampai ke penerima.']].map(([t,d],i)=><article key={t}><b>{i+1}</b><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
  <section className="donation-options">{flow.map(([img,title,desc,action],i)=><article key={title}><header><div className={'option-icon c'+i}>{i+1}</div><div><h3>{i+1}. {title}</h3><p>{desc}</p></div></header><img src={'/'+img} alt="" />{i===1?<button disabled>{action}<span>Segera hadir</span></button>:<a href={i===2?'#verified':'#alur'}>{action} →</a>}</article>)}</section>
  <section className="why"><h2>Mengapa Berdonasi di KEMBALI?</h2><div>{[['⌁','Tersalurkan Tepat Sasaran','Donasimu akan disalurkan kepada penerima yang benar-benar membutuhkan.'],['♻','Dukung Ekonomi Sirkular','Mengurangi limbah dengan memanfaatkan kembali barang agar bernilai.'],['♢','Transparan & Terpercaya','Proses donasi transparan dan dapat dipantau setiap saat.'],['♧','Bersama Komunitas','Berkolaborasi dengan komunitas, relawan, dan bank sampah.']].map(([icon,t,d])=><article key={t}><b>{icon}</b><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
  <section className="verified" id="verified"><h2>Komunitas Terverifikasi</h2><div className="verified-grid">{partners.map(([img,name,desc])=><article key={name}><img src={'/'+img} alt="" /><h3>{name}</h3><p>{desc}</p></article>)}</div></section>
  <section className="donation-impact"><div><h2>Siap Memberikan Kehidupan<br/>Kedua untuk Barangmu?</h2><p>Salurkan barang layak pakai ke komunitas yang membutuhkan hanya dalam beberapa langkah mudah.</p></div><div>{stats.map(([n,l])=><article key={l}><strong>{n}</strong><span>{l}</span></article>)}</div><img src="/Donation Streamline Bruxelles.svg" alt="" /></section>
  <Footer/>
</main>}
